

const arr = [
  {
    name: "Norman P. Chan",
    company: "Integer Tincidunt Corp.",
    price: "$6.76",
    stars: 4,
  },
  {
    name: "Amelia N. Lloyd",
    company: "A Aliquet Corporation",
    price: "$2.91",
    stars: 5,
  },
  {
    name: "Giselle O. Mayer",
    company: "Nunc Ac PC",
    price: "$5.25",
    stars: 5,
  },
  {
    name: "Brennan Z. Salinas",
    company: "Suspendisse Aliquet Molestie Corporation",
    price: "$5.86",
    stars: 4,
  },
  {
    name: "Erin Q. Lucas",
    company: "Mauris Elit Industries",
    price: "$5.61",
    stars: 2,
  },
  {
    name: "Margaret Z. Bean",
    company: "Turpis Vitae Purus Ltd",
    price: "$8.09",
    stars: 3,
  },
  {
    name: "Kevin K. Arnold",
    company: "In Tempus LLC",
    price: "$6.71",
    stars: 3,
  },
  {
    name: "Drew K. Oconnor",
    company: "Mollis Non Cursus Limited",
    price: "$4.90",
    stars: 4,
  },
  {
    name: "Jin D. Rosales",
    company: "Mus Associates",
    price: "$8.92",
    stars: 2,
  },
  {
    name: "Cadman R. Blanchard",
    company: "A Feugiat Tellus Associates",
    price: "$8.53",
    stars: 1,
  },
  {
    name: "Hermione C. Hansen",
    company: "A Tortor Nunc Limited",
    price: "$4.50",
    stars: 5,
  },
  {
    name: "Omar K. Cook",
    company: "Mauris Molestie Pharetra Company",
    price: "$3.77",
    stars: 1,
  },
  {
    name: "Branden L. Pierce",
    company: "Fusce Dolor Inc.",
    price: "$4.09",
    stars: 4,
  },
  {
    name: "Lacy F. Townsend",
    company: "Odio Vel Est Company",
    price: "$5.29",
    stars: 3,
  },
  {
    name: "Troy M. Colon",
    company: "Ac Turpis Egestas Limited",
    price: "$8.90",
    stars: 3,
  },
  {
    name: "Zephr Q. Gamble",
    company: "Nunc Mauris Elit LLP",
    price: "$3.44",
    stars: 5,
  },
  {
    name: "Claudia Q. Alexander",
    company: "Aliquam Iaculis Industries",
    price: "$2.87",
    stars: 2,
  },
  {
    name: "Victoria Q. Mcdonald",
    company: "Fermentum LLC",
    price: "$7.33",
    stars: 3,
  },
  {
    name: "Angela Z. Washington",
    company: "Eget Volutpat Corporation",
    price: "$7.24",
    stars: 2,
  },
  {
    name: "Venus S. Clark",
    company: "Sem LLC",
    price: "$6.80",
    stars: 3,
  },
  {
    name: "Octavius A. Carey",
    company: "Tellus Corp.",
    price: "$9.20",
    stars: 1,
  },
  {
    name: "Carly M. Sanders",
    company: "Nisi Foundation",
    price: "$4.90",
    stars: 5,
  },
  {
    name: "Philip W. Kennedy",
    company: "Praesent Luctus LLC",
    price: "$2.29",
    stars: 2,
  },
  {
    name: "Britanney E. Little",
    company: "Elit A Corp.",
    price: "$2.69",
    stars: 5,
  },
  {
    name: "Jerry T. Robinson",
    company: "Gravida LLP",
    price: "$2.18",
    stars: 3,
  },
  {
    name: "Alvin F. Melendez",
    company: "Velit Sed Malesuada Foundation",
    price: "$2.82",
    stars: 3,
  },
  {
    name: "Cade Y. Oliver",
    company: "Vel Vulputate Eu Limited",
    price: "$8.64",
    stars: 5,
  },
  {
    name: "Isabella T. Harris",
    company: "Elit Company",
    price: "$3.52",
    stars: 4,
  },
  {
    name: "Luke S. Maynard",
    company: "Scelerisque Dui Industries",
    price: "$8.84",
    stars: 4,
  },
  {
    name: "Cameran B. Chandler",
    company: "Vehicula Aliquet Libero LLP",
    price: "$5.17",
    stars: 3,
  },
  {
    name: "Carolyn Z. Booker",
    company: "Nulla Institute",
    price: "$9.27",
    stars: 2,
  },
  {
    name: "Piper J. Page",
    company: "Amet Nulla Company",
    price: "$7.22",
    stars: 4,
  },
  {
    name: "Fatima H. Patterson",
    company: "Euismod In LLP",
    price: "$9.81",
    stars: 3,
  },
  {
    name: "Nora H. Humphrey",
    company: "Elit A Feugiat Associates",
    price: "$4.57",
    stars: 3,
  },
  {
    name: "Troy O. Wilkins",
    company: "Neque Industries",
    price: "$8.05",
    stars: 2,
  },
  {
    name: "Glenna Z. Conway",
    company: "Aliquam LLP",
    price: "$5.41",
    stars: 3,
  },
  {
    name: "Astra W. Wilder",
    company: "Pharetra Limited",
    price: "$6.93",
    stars: 1,
  },
  {
    name: "Latifah W. Gill",
    company: "Orci Corp.",
    price: "$3.88",
    stars: 5,
  },
  {
    name: "Olga Q. Crawford",
    company: "Mollis Vitae Inc.",
    price: "$3.41",
    stars: 2,
  },
  {
    name: "Rebecca J. Rivas",
    company: "Enim Sed Nulla Ltd",
    price: "$5.30",
    stars: 4,
  },
  {
    name: "Uta I. Caldwell",
    company: "Lorem Semper Auctor Ltd",
    price: "$9.79",
    stars: 1,
  },
  {
    name: "Colby N. Huffman",
    company: "Aliquet Proin Corporation",
    price: "$9.33",
    stars: 4,
  },
  {
    name: "Maite Q. Kline",
    company: "Risus Corporation",
    price: "$7.70",
    stars: 2,
  },
  {
    name: "Brielle N. Jefferson",
    company: "Aliquam Foundation",
    price: "$7.40",
    stars: 4,
  },
  {
    name: "Hadassah W. Mercado",
    company: "Enim Foundation",
    price: "$8.71",
    stars: 5,
  },
  {
    name: "Jason P. Hyde",
    company: "Sed Corp.",
    price: "$6.46",
    stars: 4,
  },
  {
    name: "Ashton K. Brooks",
    company: "Duis Elementum Company",
    price: "$4.11",
    stars: 2,
  },
  {
    name: "Alfonso X. Forbes",
    company: "Nunc LLC",
    price: "$5.54",
    stars: 4,
  },
  {
    name: "Christian I. Campos",
    company: "Amet PC",
    price: "$8.17",
    stars: 2,
  },
  {
    name: "Armando T. Banks",
    company: "Sagittis Felis Limited",
    price: "$2.74",
    stars: 3,
  },
  {
    name: "Harriet G. Mack",
    company: "Penatibus Et Company",
    price: "$8.43",
    stars: 1,
  },
  {
    name: "Asher L. Bowen",
    company: "Urna Suscipit LLC",
    price: "$5.05",
    stars: 1,
  },
  {
    name: "Christen N. Morse",
    company: "Vel Sapien Imperdiet Institute",
    price: "$7.21",
    stars: 3,
  },
  {
    name: "Carol H. Livingston",
    company: "Suspendisse Non Leo Consulting",
    price: "$5.28",
    stars: 4,
  },
  {
    name: "Chava F. Terry",
    company: "Ultricies Adipiscing Corp.",
    price: "$2.91",
    stars: 5,
  },
  {
    name: "Wing Q. Jimenez",
    company: "Aliquam Auctor Velit Consulting",
    price: "$3.06",
    stars: 2,
  },
  {
    name: "Boris E. Bird",
    company: "Risus PC",
    price: "$3.03",
    stars: 2,
  },
  {
    name: "Tashya K. Barlow",
    company: "Luctus Et Ultrices Incorporated",
    price: "$6.40",
    stars: 2,
  },
  {
    name: "Troy N. Benson",
    company: "Nulla Corp.",
    price: "$6.22",
    stars: 3,
  },
  {
    name: "Herman X. Dotson",
    company: "Fames Incorporated",
    price: "$9.97",
    stars: 1,
  },
  {
    name: "Imani U. Wong",
    company: "In Corp.",
    price: "$7.11",
    stars: 1,
  },
  {
    name: "Amal B. Head",
    company: "Bibendum Fermentum Corporation",
    price: "$5.96",
    stars: 1,
  },
  {
    name: "Bert E. Acevedo",
    company: "Sodales Purus Limited",
    price: "$9.39",
    stars: 3,
  },
  {
    name: "Merrill N. Roach",
    company: "Dolor Corporation",
    price: "$2.20",
    stars: 1,
  },
  {
    name: "Amery T. Mccormick",
    company: "Lorem LLP",
    price: "$3.26",
    stars: 1,
  },
  {
    name: "Levi T. Mcfarland",
    company: "Hendrerit Corporation",
    price: "$9.05",
    stars: 5,
  },
  {
    name: "Denton J. Beasley",
    company: "Et Magnis Dis Foundation",
    price: "$9.05",
    stars: 1,
  },
  {
    name: "Medge F. Lang",
    company: "Arcu Limited",
    price: "$7.32",
    stars: 3,
  },
  {
    name: "Beck I. Livingston",
    company: "At Sem Molestie Consulting",
    price: "$6.25",
    stars: 3,
  },
  {
    name: "Timothy T. Davenport",
    company: "Etiam Corp.",
    price: "$7.89",
    stars: 5,
  },
  {
    name: "Harriet L. Hines",
    company: "Ac Metus Company",
    price: "$8.09",
    stars: 1,
  },
  {
    name: "Ima R. Soto",
    company: "Praesent Luctus Corporation",
    price: "$5.23",
    stars: 4,
  },
  {
    name: "Stephen A. Garza",
    company: "Luctus Sit Inc.",
    price: "$3.01",
    stars: 2,
  },
  {
    name: "Honorato Y. Daugherty",
    company: "Facilisis Lorem PC",
    price: "$9.22",
    stars: 5,
  },
  {
    name: "Phoebe B. Goodwin",
    company: "Sed Incorporated",
    price: "$6.21",
    stars: 4,
  },
  {
    name: "Sylvia F. Castillo",
    company: "Vehicula Et Rutrum Institute",
    price: "$8.17",
    stars: 4,
  },
  {
    name: "Regina O. Nguyen",
    company: "Diam Lorem Auctor PC",
    price: "$4.12",
    stars: 4,
  },
  {
    name: "Andrew U. Griffin",
    company: "Praesent Eu Nulla Consulting",
    price: "$2.23",
    stars: 4,
  },
  {
    name: "Daniel J. Vaughan",
    company: "Sociis Natoque Company",
    price: "$6.34",
    stars: 4,
  },
  {
    name: "Jane Y. Stewart",
    company: "Libero Donec Consectetuer Company",
    price: "$5.56",
    stars: 3,
  },
  {
    name: "Porter C. Booker",
    company: "Ipsum Nunc Id Company",
    price: "$3.78",
    stars: 3,
  },
  {
    name: "Cody G. Huber",
    company: "Cursus In Company",
    price: "$5.61",
    stars: 3,
  },
  {
    name: "Griffin N. Lang",
    company: "Suspendisse Ac Metus Foundation",
    price: "$5.02",
    stars: 3,
  },
  {
    name: "Jasper N. Blankenship",
    company: "Interdum Sed Ltd",
    price: "$9.39",
    stars: 4,
  },
  {
    name: "Andrew Q. Jarvis",
    company: "Nec Leo PC",
    price: "$4.14",
    stars: 2,
  },
  {
    name: "Lucy Z. Buckner",
    company: "Porttitor Vulputate Posuere Industries",
    price: "$8.46",
    stars: 2,
  },
  {
    name: "Colton T. Bush",
    company: "Montes Nascetur Ridiculus LLP",
    price: "$8.27",
    stars: 5,
  },
  {
    name: "Tucker S. Cohen",
    company: "Nulla Tempor Corporation",
    price: "$9.20",
    stars: 4,
  },
  {
    name: "Nicholas R. Cole",
    company: "Massa Company",
    price: "$8.05",
    stars: 1,
  },
  {
    name: "Nola Y. Alexander",
    company: "Nunc LLC",
    price: "$7.40",
    stars: 3,
  },
  {
    name: "Flynn K. Charles",
    company: "Vitae Aliquet Inc.",
    price: "$6.35",
    stars: 4,
  },
  {
    name: "Wayne J. Yates",
    company: "Odio Institute",
    price: "$3.89",
    stars: 3,
  },
  {
    name: "Grace D. Sykes",
    company: "Praesent Corporation",
    price: "$8.69",
    stars: 2,
  },
  {
    name: "Conan S. Hays",
    company: "A Neque Nullam Company",
    price: "$9.44",
    stars: 3,
  },
  {
    name: "Brielle I. Bright",
    company: "Ornare Elit Inc.",
    price: "$5.76",
    stars: 5,
  },
  {
    name: "Wendy V. Farley",
    company: "Amet Risus Consulting",
    price: "$8.81",
    stars: 1,
  },
  {
    name: "Conan J. Gray",
    company: "Odio Semper LLC",
    price: "$8.11",
    stars: 4,
  },
  {
    name: "Whitney C. Townsend",
    company: "Ac Corporation",
    price: "$3.23",
    stars: 3,
  },
  {
    name: "Acton P. Henry",
    company: "Luctus Institute",
    price: "$6.82",
    stars: 4,
  },
  {
    name: "Emily K. Farmer",
    company: "Ipsum Sodales Inc.",
    price: "$5.49",
    stars: 4,
  },
];
